/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyncIndexRouteImport } from './routes/sync/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIndexRoute = SyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sync/': typeof SyncIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/sync': typeof SyncIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sync/': typeof SyncIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse/'
    | '/search/'
    | '/settings/'
    | '/sources/'
    | '/sync/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/search' | '/settings' | '/sources' | '/sync'
  id:
    | '__root__'
    | '/'
    | '/browse/'
    | '/search/'
    | '/settings/'
    | '/sources/'
    | '/sync/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  SyncIndexRoute: typeof SyncIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/': {
      id: '/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof SyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  SyncIndexRoute: SyncIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
